MOVEON/Models/ApplicationsDbcontext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace MOVEON.Models
{
    public class ApplicationsDbcontext:DbContext
    {
        public ApplicationsDbcontext() : base("Data Source=CHETUIWK802\\SQLEXPRESS;" +
            "Initial Catalog=EmpList;Integrated Security=True;Pooling=False") { }
        public DbSet<Employess> employesses { get; set; }
    }
}

MOVEON/Models/Employess.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MOVEON.Models
{
    public class Employess
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string Mobile { get; set; }
        public string Add{ get; set; }


    }
}

MOVEON/Controllers/EmployessController.cs
using MOVEON.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MOVEON.Controllers
{
    
    public class EmployessController : Controller
    {

        ApplicationsDbcontext stb = new ApplicationsDbcontext();
        public ActionResult Index()
        {
            var Employess = stb.employesses.ToList();
            return View(Employess);
        }
       
        public ActionResult create()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult create(Employess emp)
        {
            stb.employesses.Add(emp);
           stb.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MOVEON/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MOVEON.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MOVEON/Views/Employess/Index.cshtml
@model IEnumerable<MOVEON.Models.Employess>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("Add Employe","create","Employess")
<table class=" table table-bordered">
    <tr>
        <th>ID</th>
        <th>NAME</th>
        <th>GENDER</th>
        <th>AGE</th>
        <th>MOBILE</th>
        <th>ADDRESS</th>
        <th>ACTION</th>
    </tr>
    @foreach(var ptb in Model)
            {
<tr>
    <td>@ptb.Id</td>
    <td>@ptb.Name</td>
    <td>@ptb.Gender</td>
    <td>@ptb.Age</td>
    <td>@ptb.Mobile</td>
    <td>@ptb.Add</td>
</tr>
            }
</table>

MOVEON/Views/Employess/create.cshtml
@{
    ViewBag.Title = "Add Employee";
}


<div class="row">
    <div class="col-6 offset-3">
      <div class="card">
          <div class="card-header">
              <h3>ADD EMPLOYEE</h3>
          </div>
          <div class="card-body">
              @using (Html.BeginForm("create", "Employess", FormMethod.Post))
              {
                  <div class="form-group">
                      <label>Employe Name</label>
                      <input type="text" class="from-controil" name="NAME" />
                  </div>
                  <div class="form-group">
                      <label>Employe Gender</label>
                      <select class="from-controil" name="GENDER">
                          <option value="">select</option>
                          <option value="Male">Male</option>
                          <option value="Female">Female</option>
                      </select>
                  </div>
                  <div class="form-group">
                      <label>Employe Age</label>
                      <input type="number" class="from-controil" name="AGE" />
                  </div>
                  <div class="form-group">
                      <label>Employe Moblie</label>
                      <input type="text" class="from-controil" name="MOBILE" />
                  </div>
                  <div class="form-group">
                      <label>Employe Add</label>
                      <input type="text" class="from-controil" name="Add" />
                  </div>
                  <div class="form-group">
                      <input type="submit" value="Submit" class="btn btn-info" />
                  </div>
              }
          </div>
      </div>

    </div>

</div>

MOVEON/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MOVEON/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MOVEON/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MOVEON/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>